version: "3.8"
services: 
    client:
        build: .
        ports:
            - 3000:3000
        volumes: 
            - type: bind
              source: .
              target: /app
            - type: volume
              target: /app/node_modules
    test:
        build: .
        command: ["npm","run","test"]
        volumes: 
            - type: bind
              source: .
              target: /app
            - type: volume
              target: /app/node_modules
        stdin_open: true
        tty: true